language: python
python:
  - "3.5"
services:
  - docker
env:
  - REDIS_VERSION=3.0.7
  - REDIS_VERSION=3.2.13
  - REDIS_VERSION=4.0.14
  - REDIS_VERSION=5.0.5
script:
  docker build --build-arg redis_version=$REDIS_VERSION -t grokzen/redis-cluster .
