services:
  clickhouse:
    container_name: clickhouse
    image: bitnami/clickhouse:latest
    restart: on-failure
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 2s
      retries: 20
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "8123:8123"
      - "9000:9000"
    
