version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

#networks:
#  default:
#    external:
#      name: shared