version: '3'
services:
  openldap:
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=admin@demo.com,user@demo.com
      - LDAP_PASSWORDS=abcd1234,abcd1234
    volumes:
      - './openldap_data:/bitnami/openldap'