version: '3.7'

services:
  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    ports: [ 8126:8126 ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    environment:
      DOCKER_CONTENT_TRUST: 1
      DD_API_KEY: ${DD_API_KEY:-no_datadog_api_key}
      DD_SITE: ${DD_SITE:-datadoghq.com}
      DD_APM_ENABLE: "false"
      DD_LOGS_ENABLED: "false"
      DD_CONTAINER_EXCLUDE: "${DD_CONTAINER_EXCLUDE:-name:*datadog-agent*}"
      DD_CONTAINER_INCLUDE: "${DD_CONTAINER_INCLUDE:-name:*}"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
