apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    name: keycloak
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      name: keycloak
      labels:
        app: keycloak
        name: keycloak
    spec:
      restartPolicy: Always
      containers:
      - name: keycloak
        image: jboss/keycloak:6.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1024Mi
        env:
          - name: KEYCLOAK_USER
            value: "admin"
          - name: KEYCLOAK_PASSWORD
            value: "admin"
          - name: DB_VENDOR
            value: "postgres"
          - name: DB_USER
            value: "keycloak"
          - name: DB_PASSWORD
            value: "password"
          - name: DB_ADDR
            value: "keycloakdb-postgresql"
          - name: DB_PORT
            value: "5432"
          - name: DB_DATABASE
            value: "keycloakdb"
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"