version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    platform: linux/amd64
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1!
    ports:
      - "1433:1433"
    volumes:
      - .data:/var/opt/mssql