version: '3.8'

services:
  zitadel:
    image: ghcr.io/zitadel/zitadel:${ZITADEL_VERSION:-latest}
    command: start-from-init --masterkeyFromEnv --tlsMode disabled --config /config/zitadel.yaml
    env_file:
      - .env
    environment:
      ZITADEL_MASTERKEY: ${ZITADEL_MASTERKEY:-MasterkeyNeedsToHave32Characters}
      ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_VERIFIERS: pbkdf2
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - zitadel
      - data
    ports:
      - 9000:8080
    volumes:
      - ./config:/config:ro

  db:
    image: postgres:15
    restart: always
    networks:
      - data
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "${POSTGRES_PORT:-15432}:5432"

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #      - ./data/pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - data
  #   restart: unless-stopped

networks:
  zitadel:
  data: