version: '3.5'

services:
  livekit:
    image: livekit/livekit-server:v1.6
    command: --dev --config /etc/livekit.yaml
    restart: unless-stopped
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882"
      - "7889:7889"
      - "50100-50200:50100-50200"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
  ingres:
    image: livekit/ingress:latest
    environment:
      - INGRESS_CONFIG_FILE=/etc/ingress.yaml
    volumes:
      - ./ingress.yaml:/etc/ingress.yaml
  egress:
    image: livekit/egress:v1.8
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress.yaml
    volumes:
      - ./egress.yaml:/etc/egress.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - CAP_SYS_ADMIN