redis:
    address: host.docker.internal:6379
    username: ""
    password: ""
    db: 0
    use_tls: false
    sentinel_master_name: ""
    sentinel_username: ""
    sentinel_password: ""
    sentinel_addresses: []
    cluster_addresses: []
    max_redirects: null
api_key: APIiWXGfvH4CXVu
api_secret: cfVu3xm4duPQGVWEmqyBasdtAT8ndchxo2KpjqylP3T
ws_url: wss://livekit.local
rtmp_port: 1935
whip_port: 8080
http_relay_port: 9090
logging:
    json: false
    level: ""
development: false
rtc_config:
    udp_port: 7885
    use_external_ip: true
    enable_loopback_candidate: false
