version: '3.5'

services:
  nsqlookupd:
    image: nsqio/nsq
    platform: linux/amd64
    command: /nsqlookupd
    ports:
      - '4160'
      - '4161'
    logging:
      driver: none

  nsqd:
    image: nsqio/nsq
    platform: linux/amd64
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - '4150:4150'
      - '4151:4151'
    logging:
      driver: none

  nsqadmin:
    image: nsqio/nsq
    platform: linux/amd64
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - '4171:4171'
    logging:
      driver: none
