version: '3.1'
services:
    redis: 
        container_name: redis
        image: redis
        restart: always
        ports:
            - 6379:6379
        volumes:
        - ./.redis-data:/var/lib/redis